// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcxfsiglgvknckwdcxcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjeGZzaWdsZ3ZrbmNrd2RjeGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNjkwMDIsImV4cCI6MjA2ODY0NTAwMn0.fZi9uTr6sXM5bRLBbdAkD9mzt7H3QtWkR-gZortusU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});